os: unstable
environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: cAnrfSL5eT7o7i/UyXHYEgXB9c6DOzhh4k5UmVLfYHvYHf1lcltIwjpx0EOBVpWA

  matrix:
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"
  - nodejs_version: "7"
  - nodejs_version: "8"
  
platform:
  - x64
  - x86
  
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%PATH%
  # install submodules
  - git submodule update --init
  # install modules
  - npm install -g node-gyp node-pre-gyp node-pre-gyp-github
  - npm install
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('[publish binary]')) { node-pre-gyp package; node-pre-gyp-github publish --release }

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
